### ISSUE TITLE
remove urls from module information

### ISSUE THREAD

**Issue by stefanheine** [thenativeweb/reqd#5]
reqd outputs the module names and their url. please remove the url, as that doesn't really add value but makes the output long and hard to read.

**Comment by goloroden** [comment]
Can you please explain what you mean by `url`?
Can you provide an example of what currently happens and show what you would like to have?

**Comment by stefanheine** [comment]
in the earlier version of reqd I had tested, you had not shown the used version, but the url to the package, but that has been changed in the meantime.

ok to close.

**Comment by goloroden** [comment]
Okay, thanks :-)
