### ISSUE TITLE
can't handle scoped packages

### ISSUE THREAD

**Issue by stefanheine** [thenativeweb/reqd#6]
I have a package directory:
module1

but the package.json contains a scoped package name:
  "name": "@<user>/module1"

reqd does not read the 'name' from the package, and only searches for 'module1' - since the other modules contain a reference to the scoped name, it won't find the dependency:
      "@<user>/module1": "0.2.6"

**Comment by goloroden** [comment]
I am not sure whether I got your bug description right.

Supposed you have a scoped module `@foo/bar`, and you want to find out which other module uses `@foo/bar`. If you run

```bash
$ reqd @foo/bar
```

everything works fine, AFAICS.

Can you please provide more details on how to reproduce the questionable behavior, what the actual result is, and your expected result is?

**Comment by stefanheine** [comment]
I have a package '@myname/package' which is stored in the 'package' directory (without the @myname scope prefix).
my assumption was that 'reqd package' would go into the 'package' directory, read the package.json to get the real name (including the scope prefix), and then search for this.
in the meantime, I realized that I have to give the package name including the scope, instead of the directory name.

**Comment by goloroden** [comment]
Yep :-)
