### ISSUE TITLE
in output, show currently used version

### ISSUE THREAD

**Issue by stefanheine** [thenativeweb/reqd#7]
currently the output shows all modules using the given module. in addition to that information, I would like to see what version of the given module is currently used, so I know who outdated the version is.

**Comment by goloroden** [comment]
I guess I got your question wrong, but the information

> what version of the given module is currently used

is already shown in `reqd`'s output. E.g., when you run

```bash
$ reqd lodash
```

the output will be something such as:

```bash
foo (4.6.1)
bar (3.10.1)
baz (4.14.1)
```

The version numbers shown are the versions of `lodash` being used in the modules `foo`, `bar`, and `baz`.

Can you please provide more details on what you are missing?

**Comment by stefanheine** [comment]
ok to close (either I missed this, or it was introduced in a newer version that what I was testing at that time).

**Comment by goloroden** [comment]
Okay, thanks :-)
